export const INTERNAL_ERRORS_CODE = {
  VALIDATION_FASTIFY: "Err0001",
  VALIDATION_ZOD: "Err0002",
  FAILED_GENERATE_IDENTIFIER: "Err0003",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
};
