export const EPOCH = 1704067200000n;

export const WORKER_ID_BITS_COMPACT = 5n;
export const SEQUENCE_BITS_COMPACT = 5n;

export const MAX_WORKER_ID = (1n << WORKER_ID_BITS_COMPACT) - 1n;
export const MAX_SEQUENCE = (1n << SEQUENCE_BITS_COMPACT) - 1n;

export const WORKER_ID_SHIFT = SEQUENCE_BITS_COMPACT;
export const TIMESTAMP_SHIFT = SEQUENCE_BITS_COMPACT + WORKER_ID_BITS_COMPACT;
export const MAX_WORKER_ID_NUMBER = Number(MAX_WORKER_ID);